### ISSUE TITLE
just FYI Amundsen data portal project

### ISSUE THREAD

**Issue by feng-tao** [gtoonstra/databook#10]
@gtoonstra , just FYI that Lyft has built a data portal project named Amundsen, which is also inspired by Airbnb data portal. Our project is now open source:

- https://github.com/lyft/amundsenfrontendlibrary

- https://github.com/lyft/amundsenmetadatalibrary

- https://github.com/lyft/amundsensearchlibrary

- https://github.com/lyft/amundsendatabuilder

The last repo will be a extractor/model library repo which is intent to be using in Airflow DAG. We put some examples on how to use that library in an Airflow DAG.

Thanks,

**Comment by gtoonstra** [comment]
That is awesome! Thanks for letting me know. I put a note about this in the README of the repo.

**Comment by feng-tao** [comment]
thanks @gtoonstra
