### ISSUE TITLE
Extract sql queries from a tableau dashboard

### ISSUE THREAD

**Issue by gtoonstra** [gtoonstra/databook#4]
Use an API to connect to Tableau and extract the quer(ies) used to populate a dashboard. Try to extract with the API to with datasource it connects to identify the database.
I've written a library called "sqlineage" that helps to find out the tables that are involved in the query, which should make it possible to establish relationships between the tableau dashboard and the underlying datasources.

**Comment by jornh** [comment]
We are standing up a Tableau server environment at my work as we speak. So naturally I'm interested in being able to extract info from there and consolidate into our "people & data graph".

So, just trying to understand a bit more about the scope of this issue: I presume this is now already halfway kicked off on the "use an API" part with https://github.com/gtoonstra/databook/commit/9b0c03739c91a756bc04e369d14b9a4065cf7cad ?? 

But that it still need to be combined with using https://pypi.python.org/pypi/sqlineage and do "magic" ... or at least exacting?

> Side Note: So far I'm still not fully there with having a dev environment with Docker + WSL up (see #8 somehow `ldap3` also gave me some grief inside docker BTW). So this is more to signal an interest in the project as a whole + that I think there's common ground to work on stuff (when I can get up to speed) and also to basically get a bit of conversation going 🙂 - so please don't wait for me to do anything on this Tableau issue if you are hacking on it already ...
>
> To add a bit more flavor about our environment: In addition to Tableau now, we're currently using Airflow with DAGs and SQL in a GitHub repo, StreamSets, AWS S3 + Redshift, SQL Server etc.
